language: node_js
node_js: 12.18.3

cache:
  directories:
    - 'node_modules'
install:
  - npm i -g codecov
  - npm i
after_success:
  - codecov

deploy:
  - provider: npm
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true
      repo: jumakiwaka/cheap-stocks-cli
    email: $NPM_EMAIL
